### PR TITLE
Add support for Palm, Claude-2, Llama2, CodeLlama (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM allows you to use any LLM as a drop in replacement for `gpt-3.5-turbo` 

In addition LiteLLM client allows you to:
* A/B test LLMs in production 
* Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)
* Logging to view input/outputs for each LLM

Here's a link to a live demo of litellm client: https://admin.litellm.ai/ 

liteLLM-Ab-testing

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@tju01 can you please take a look at this PR when possible ? Happy to add docs/tests if this initial commit looks good😊

**Comment by tju01** [comment]
Hi,

Thank you for your contribution. Unfortunately, I'm not interested in this change right now. There are a few reasons for this:
1. The `OpenAIBase` class is also used for other providers that use an OpenAI-style API, like FastChat. The `api_base` is always set explicitly and using `litellm` like that would therefore not actually add support for other providers. Apart from the fact that apparently the `api_base` also needs to be set through `custom_api_base` from what I can see, so the PR won't work like that, but that's a minor point.
2. I'm not interested in other providers right now. I don't even have access to models like Claude and don't know about Cohere.
3. The library does seem like a pretty big abstraction layer with all the features it provides, none of which I'm really interested in. I would like to keep things simple instead and don't have added abstraction through this library.

I might reconsider this if I sometimes add support for other API providers, but for now I'm mostly focused on open source models and don't really need this.

**Comment by ishaan-jaff** [comment]
- Why does the library seem like a big abstraction layer ? (the goal of litellm is to be lightweigt to call diff LLMs)


- If you're focused on adding support for Open Source models why not use LiteLLM - we provide one interface for hugging face, together ai, baseten and custom deployment solns 


Thanks for the feedback @tju01

**Comment by tju01** [comment]
For the abstraction, I was just looking at all the features that the library has. I have not looked that much at the code, it just seemed to me that a library that provides features like this:

> Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)

is not lightweight anymore from my perspective. Same for all the integrations that it seems to provide from when I had a quick look at the issues. Again, I have not looked _too_ deeply into it given the other reasons that I listed, but it just seemed like that.

---

For the open source models, from what I can see you just provide the client which is by far the simpler part and not really something that is a problem in my current code. And even for the bit of code for the client, litellm is insufficient:
- For vLLM, I can't use it
- For TGI, I need it to support a local TGI instance controlled by the same program and not some "huggingface inference endpoints". I also need to control things like prompt templates myself which [litellm seems to do it itself in a very bad way](https://github.com/BerriAI/litellm/blob/6aff47083be659b80e00cb81eb783cb24db2e183/litellm/llms/huggingface_restapi.py#L37).
- For HF transformers, meaning really the `transformers` library and not something else like TGI I again can't use it.

Also ayncio [seems to be implemented]( https://github.com/BerriAI/litellm/blob/adcf3dfe74854827938af34f3c59c6329c1ecd72/litellm/main.py#L48) using threads with `loop.run_in_executor(None, ...)` which [is just not going to work when I run >1k requests at the same time](https://github.com/FastEval/FastEval/pull/78#issuecomment-1703241377). Which I am doing and which also works fine with asyncio. I know other people that use some HF inference endpoints or whatever won't do this in the first place, but FastEval is about running evaluations locally and for maximum performance running that many requests at the same time is actually sometimes required.

**Comment by krrishdholakia** [comment]
Thanks for the feedback @tju01 

- vLLM: We can add support for this. https://github.com/BerriAI/litellm/issues/254
- TGI: You can run this locally pretty easily - `completion(model="huggingface/<your_local_endpoint>", ...)`
- `acomplete`: what would a better solution for acomplete be? [Tracking this issue as well - https://github.com/BerriAI/litellm/issues/255]


Did I miss anything?

**Comment by tju01** [comment]
**vLLM:** For vLLM, I don't really think litellm is the right place. I was talking about local inference using the `vllm` python library. Loading models on a local GPU is not really the goal of litellm from what I understand.

---

**TGI:** For running it with a local TGI instance, ok. That wasn't clear to me, couldn't find the documentation for that that quickly.

---

**acomplete:** For `acomplete`, it would really need to be implemented using `asyncio` all the way down to the request. So use `acreate` for the OpenAI API, use the `asyncio` library for for making HTTP requests to whatever etc.. I don't really see an alternative for that and it's also how I'm currently restructuring my own codebase.

Because if there is only a blocking version of the call, then a thread is indeed required. The problem that I'm personally encountering with that also isn't really the performance overhead of threads (which doesn't really matter much here), but the fact that there are some OS limits on how many threads, file descriptors etc. can be created and active at the same time and those limits are sometimes lower than one would expect so on some machines I'm hitting them which crashes it.

Though from what I can see you wouldn't hit them anyway because you use the default ThreadPoolExecutor which has a limited number of threads and just queues requests afterwards. So it won't actually run that many requests in parallel in the first place in your case, which also isn't good. Really, in the end `asyncio` all the way down is required for it to work.

---

**Prompt templates:** One thing you missed: I really don't think the way you are implementing support for HF models is good. From the quick look I had [here](https://github.com/BerriAI/litellm/blob/6aff47083be659b80e00cb81eb783cb24db2e183/litellm/llms/huggingface_restapi.py#L47) you just take the messages from the user & assistant and concatenate them in some really simple way (except for llama2-chat where you did implement support for the template for some reason).

That's not how these models are supposed to be used. Different models need a different way to translate the conversation into a prompt string. For an example on how to actually do this correctly, have a look at [this file](https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py#L334) from the popular FastChat repository. I personally don't use their prompt templates and implement them myself, but that has to do with my requirement for evaluation which might not apply for you.

I think for FastChat, you might be able to also just import their library and use their prompt templates. Or copy them over if you want. Because I really wouldn't recommend implementing them all yourself. But just concatenating the message contents like that isn't correct and won't give actual good outputs.

**Comment by tju01** [comment]
Disclaimer: I only took a quick look at your codebase after your PR. I might have some wrong assumptions about it like in the case of local TGI instance, but also the way you implement asyncio/prompt templates/whatever. Correct me if that's the case.

**Comment by krrishdholakia** [comment]
Thank you for the feedback on the Prompt Templates - i've added an issue to track this as well: https://github.com/BerriAI/litellm/issues/257


btw I noticed your earlier comment on the api base. You can set this on the module as well - `litellm.api_base = "your custom base"`. 

@tju01  Can you help me understand why adding support for new LLMs *isn't* a priority for you?

**Comment by tju01** [comment]
Setting `litellm.api_base` won't work for me because I still use multiple models in parallel threads sometimes (still one example where I _do_ use threads even after the asyncio changes I'm making right now) and setting `litellm.api_base` before every request won't be threadsafe. It needs to be an argument, but I also saw that there is an `custom_api_base` argument or so. It was also just a note that this PR like it was submitted here won't work because it didn't take arguments like `api_base` into account and just tried a very simple replacement of openai with litellm which wouldn't be correct here.

---

I _am_ adding support for new open source models. But FastEval is primarily a tool to help open source developers develop new models, so the focus is very much on open source models. The only reason why I use OpenAI models is
1. As a baseline for open source models. But I'm not going to focus on evaluating different proprietary models. That's not the goal. The goal is to help open source model development.
2. As a judge model for evaluations that require GPT-4. But that won't be used with some other LLM, it's hardcoded and that's deliberate. It doesn't make sense conceptually to have different judge models there because all open source models need to be judged with the same model. And that's GPT-4.

Also at least personally I only have access to OpenAI models for now. I've applied for Claude a very long time ago, but they haven't given me access and I don't really care anyway. For other proprietary models, I really just don't care enough to even inform myself about them since the project is really about bringing open source models forward and evaluating proprietary models is not going to help with that.

**Comment by krrishdholakia** [comment]
Hey @tju01 we've fixed this now

cc: @ishaan-jaff as he worked on making these calls thread-safe. 


I'm also working on adding the fastchat prompt templates / improving our huggingface model support. 

I'd really appreciate any help with improving our async io calls - so we can help with your high-traffic problem. Otherwise I can get to it once I'm done with the hf work.

**Comment by tju01** [comment]
Good to hear that you are taking the feedback into account.

For the asyncio, I don't really have enough time to work on your code. It would be possible to chat or talk about it if that would help you. I finished the asyncio restructure for my own project here in the last few days and it's working pretty well so if you want to know how to generally do it I can help with that. Just don't have the time to implement it for your project.

**Pull request closed without merging**
